Add Bluetooth file transfer code
frc1418/VictiScout pull request #199
Opened 2021-05-06 18:45 UTC by AndrewLester

The transfer flow is as follows:
- Combine local JSON files into one CSV file using the combine files feature.
- Have one device turn on "central" mode to receive files, while everyone else sends files.
- The receiver device will receive all CSV files, and then can combine them again into one using the combine files feature (not yet implemented)

2021-05-06 19:38 UTC, ErikBoesen requested changes

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/bluetoothPreferences.js
> +            // This doesn't actually work, I think it's disabled
On the school computers?

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/device.js
> +class Device extends EventEmitter {
ES6 is crazy huh

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/device.js
> +        receiveButton.textContent = "Receive";
'

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/device.js
> +            button: deviceElem.querySelector('.receive-button')
Drop an extra comma at the end of this line for the consistency

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/transfer.js
> +const statusStates = {
If this is the only place you're declaring these state names? Might be worth making a separate enum or something

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/transfer.js
> +        if (state === 'poweredOn') {
Yet another good argument for using an enum

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/transfer.js
> +
Too many newlines?

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/transfer.js
> +}
`removeDevice` and `removeDevices` could definitely be optimized. Have you considered simply looping through (in the positive direction) and running `device.removeElement()` for each, then just setting `devices = []`?

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/transfer.js
> +}
At the very least, you're currently indexing into `devices` to get the `i`th element, then using `devices.indexOf` once it's passed to `removeDevice`, so you might want to refactor to make those operations not cancel out.

2021-05-06 19:38 UTC, ErikBoesen commented on js/transfer/util.js
> +}
Bruh I basically wrote this exact same function for a schoology microservice last week

2021-05-06 19:38 UTC, ErikBoesen commented on package.json
> +    "package-win": "electron-packager . --platform=win32 --icon=images/logo/logo.ico --arch=all --out dist/ --overwrite"
YOOOOOOOOOOO

2021-05-06 19:38 UTC, ErikBoesen commented on package.json
> +    "electron-packager": "^15.2.0",
Jesus Christ this has been a long time coming

2021-05-06 19:38 UTC, ErikBoesen commented on transfer.html
> +    <meta charset="UTF-8">
Isn't `utf-8` usually written lowercase in these meta tags? Maybe it doesn't matter but I feel like lowercase is the standard...

2021-05-06 19:38 UTC, ErikBoesen commented on transfer.html
> +                <label for="main-checkbox">Become central device:</label>
Somehow the choice of the verb "become" doesn't make sense because this is a checkbox. This caption might make more sense on a button.

2021-05-06 19:38 UTC, ErikBoesen commented on transfer.html
> +                <label for="main-checkbox">Become central device:</label>
Also, optional: I don't love the term "central"... consider picking a different name that communicates what this status is a little better. Parent? Host? Hub? Your choice. (Just definitely avoid "master" and "slave").

2021-05-06 19:38 UTC, ErikBoesen commented on transfer.html
> +                        <use href="images/transfer/bluetooth_searching.svg#icon"></use>
This is a big brain move, I've been trying to figure out how to store an SVG in a separate file while still being able to change its color since literally middle school

2021-05-06 19:38 UTC, ErikBoesen commented on transfer.html
> +            <img>
?

2021-05-06 19:38 UTC, ErikBoesen commented on transfer.html
> +    <script src="./js/transfer/transfer.js"></script>
Why use the leading `./`? You may need it for `require` but not here

2021-05-06 19:39 UTC, ErikBoesen commented
Should we transition all our code to ES6?

2021-05-06 19:40 UTC, ErikBoesen requested changes

2021-05-06 19:40 UTC, ErikBoesen commented on css/data.css
> +
I don't love the extra newlines between rules... especially if we're not doing it everywhere.

2021-05-06 23:43 UTC, AndrewLester commented on js/transfer/util.js
> +}
We love javascript

2021-05-06 23:44 UTC, AndrewLester commented on package.json
> +    "electron-packager": "^15.2.0",
The 11 major version upgrade.

2021-05-06 23:45 UTC, AndrewLester commented on transfer.html
> +                        <use href="images/transfer/bluetooth_searching.svg#icon"></use>
Dude this took me like an hour to figure out one day in some other instance, and now I just use it everywhere since it's so good.

2021-05-07 03:03 UTC, AndrewLester commented on js/transfer/bluetoothPreferences.js
> +            // This doesn't actually work, I think it's disabled
I think it's disabled on MacOS entirely. It still opens system preferences, but it doesn't direct to the Bluetooth panel.

2021-05-07 03:04 UTC, AndrewLester commented on js/transfer/device.js
> +class Device extends EventEmitter {
It makes you wonder why they started with prototypal stuff.

2021-05-07 03:05 UTC, AndrewLester commented on js/transfer/device.js
> +        console.log('Receiving data from', this);
It's not too bad, the console automatically shortens it and allows you to expand the properties.

2021-05-07 03:17 UTC, AndrewLester commented on js/transfer/transfer.js
> +const PERIPHERAL_NAME = 'VictiScout-' + os.userInfo().username;
I think I'll make this a separate issue, as it would require a tiny bit of research.

2021-05-20 21:01 UTC, AndrewLester commented
> Should we transition all our code to ES6?

I'm gonna leave `require` statements and such in for now as most tutorials continue to use them.

2021-05-24 00:06 UTC, AndrewLester commented on css/data.css
> +
I like it because it's the default with the formatter, so I decided to implement it in all CSS files just for consistency's sake.

2021-06-05 02:18 UTC, AndrewLester commented
@ErikBoesen do you want to give this one more once over? I've tested it between mine and my brother's laptops and it works well.

2021-06-05 21:16 UTC, ErikBoesen requested changes
Just a couple tiny tweaks

2021-06-05 21:16 UTC, ErikBoesen commented on js/data.js
> +const acceptableFileTypes = ['application/json', '.json', 'text/csv', 'csv'];
`'.json'` and `'csv'` seem to conflict a little—should there be a `.`?

2021-06-05 21:16 UTC, ErikBoesen commented on data.html
> +                <input id="input-file" type="file" accept=".json,application/json,text/csv,.csv" multiple></input>
Would be a little cleaner if you swapped `text/csv` and `.csv` in the order

2021-06-05 21:16 UTC, ErikBoesen commented on js/data.js
> +    if (blocked) alert('Some files have been blocked due to improper type. (Only accepting .json or .csv files)');
Nit: the parenthesized bit is a little weirdly phrased. Maybe `Only .json or .csv files accepted` would be more grammatical.

2021-06-05 21:16 UTC, ErikBoesen commented on css/theme.css
> +
I prefer not to add a newline between every rule. I think it just makes the code less compact in a way that doesn't actually improve readability.

2021-06-05 21:16 UTC, ErikBoesen commented on js/data.js
> +    const replacer = (key, value) => value === null ? '' : value;
`value === null ? '' : value` could be more succinctly written `value || ''`

2021-06-06 02:22 UTC, AndrewLester commented on js/data.js
> +    const replacer = (key, value) => value === null ? '' : value;
This is much cleaner, but does it present the issue of `value` being replaced by `''` in the case where `value` is `0`, even though it can exist as `0` in csv format?

2021-06-07 13:30 UTC, erikboesen-powerschool commented on js/data.js
> +    const replacer = (key, value) => value === null ? '' : value;
That is a fair point, didn't think about that. You can leave it as is.

2021-06-08 22:43 UTC, ErikBoesen approved these changes

2021-06-08 22:43 UTC, merged